# Generated by Django 4.0.2 on 2022-04-10 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0002_category_alter_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
