# Generated by Django 4.0.2 on 2022-04-10 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0004_accessories_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessories_product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='estore.category'),
        ),
    ]
