# Generated by Django 4.0.2 on 2022-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estore', '0007_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
